### ISSUE TITLE
Getting fail almost on every build without cleaning the cache on Netlify

### ISSUE THREAD

**Issue by SilencerWeb** [jlengstorf/netlify-plugin-gatsby-cache#41] opened 2020-08-31 05:00 UTC
Not sure which plugin causes this error so I hope you'll help to find out 🙂

I suppose either this plugin or [gatsby-source-wordpress-experimental](https://github.com/gatsbyjs/gatsby-source-wordpress-experimental) causes this error

I get such error almost every time when the site is being built without cleaning the cache on Netlify
 
![image](https://user-images.githubusercontent.com/20713191/91684253-5d282d00-eb70-11ea-8f52-00acde1a9f5a.png)

Thanks!

**Comment by jlengstorf** [comment] 2020-09-01 22:54
@SilencerWeb if you build locally without running `gatsby clean`, do you get this error? 

this plugin just moves a folder around, so my hunch is that this is something with the experimental WP plugin, but it's hard to say without seeing more of the error/code

the issue seems to be that the WP plugin is expecting a URL to exist that doesn't. what I don't know is if that URL is cached somewhere that's somehow incompatible with this library. if you're able to put together a minimal reproduction of this problem that we can use for debugging, that would go a _looooong_ way toward identifying the root cause

thanks!

**Comment by jlengstorf** [comment] 2020-11-03 23:37
I'm going to close this issue since it's been quiet for a while. if anyone hits this issue in the future, please open a new issue or comment here!

**Closed by jlengstorf** 2020-11-03 23:37 UTC
