### ISSUE TITLE
It's caching an older version of the image if it has the same name

### ISSUE THREAD

**Issue by sameersegal** [jlengstorf/netlify-plugin-gatsby-cache#39] opened 2020-07-14 12:41 UTC
The repo shows an updated file with the same name but what get's deployed is the older version.

**Comment by jlengstorf** [comment] 2020-07-14 15:37
hey there — if you disable this plugin, does it still happen? have you loaded the site with caching disabled to makes sure it's pulling the latest version?

**Comment by sameersegal** [comment] 2020-07-14 15:40
Yes, when I disable the plugin it gets deployed correctly. However, when I
re-enable the plugin it, I guess, used the old cache to deploy the older
version.

Finally, I changed the name of the file to ensure it works correctly.

**Comment by jlengstorf** [comment] 2020-07-15 20:58
I'll see if I can reproduce this. thanks!

**Comment by sameersegal** [comment] 2020-07-18 15:23
Hey, any luck with this? 

Also, I saw another interesting behavior with the plugin enabled:

Build one has a page /old-route
Deployed Successfully
Change /old-route to /new-route
Build and Deploy successfully

On the live site both /old-route and /new-route work.

**Comment by jlengstorf** [comment] 2020-07-21 00:42
@sameersegal have you tried that locally to make sure it's not a Gatsby behavior? I'm not sure Gatsby does garbage collection, so you may have to clear the cache to get rid of old pages

**Comment by jlengstorf** [comment] 2020-11-03 23:36
I'm going to close this issue since it's been quiet for a while. if anyone else hits this behavior, please feel free to open a new issue or comment on this one!

**Closed by jlengstorf** 2020-11-03 23:36 UTC
